In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
x=np.array([1,2,3,4,5,6])
y=np.array([10,98,8,2,3,4])

In [4]:
# w값 바꾸지 않기 위해 사용함,검증용이며 실제에서는 seed 하지 않음.
tf.random.set_seed(1234)

input_layer = tf.keras.layers.InputLayer(input_shape=(1,))
hidden_layer1 = tf.keras.layers.Dense(units=4, activation='relu')
hidden_layer2 = tf.keras.layers.Dense(units=2, activation='relu')
output_layer= tf.keras.layers.Dense(units=1)
# activation이 없으면 활성화함수 wx+b가 되어있는 것임.
model = keras.Sequential([
input_layer,
hidden_layer1,
hidden_layer2,
output_layer
])

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 8         
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
 dense_2 (Dense)             (None, 1)                 3         
                                                                 
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 4) dtype=float32, numpy=
 array([[ 0.29251337,  0.75989187, -0.26571786, -0.7405858 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[-0.8654773 , -0.49548578],
        [ 0.1983645 , -0.8919594 ],
        [ 0.9163494 , -0.80768967],
        [ 0.64525056, -0.48727846]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[-1.355187 ],
        [ 1.2045029]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [12]:
tmp=tf.keras.Model(inputs=model.input,outputs=model.layers[0].output)
tmp(x)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[0.29251337, 0.75989187, 0.        , 0.        ],
       [0.58502674, 1.5197837 , 0.        , 0.        ],
       [0.8775401 , 2.2796755 , 0.        , 0.        ],
       [1.1700535 , 3.0395675 , 0.        , 0.        ],
       [1.4625669 , 3.7994595 , 0.        , 0.        ],
       [1.7550802 , 4.559351  , 0.        , 0.        ]], dtype=float32)>